export const ROUTE_PATHS = {
  home: "/",
  login: "/login",
  passwordChange: "/auth/password-change",
  importPreview: "/imports/preview",
  masterClients: "/master/clients",
  masterProducts: "/master/products",
  masterCommonCodes: "/master/common-codes",
  returnIntake: "/returns/intake",
  returnProcessing: "/returns/processing",
  returnClosing: "/returns/closing",
  returnExternalOutbound: "/returns/external-outbound",
  returnHold: "/returns/hold",
  returnDisposal: "/returns/disposal",
  returnHistory: "/returns/history",
  inventoryCurrent: "/inventory/current",
  inventoryEvents: "/inventory/events",
  forbidden: "/forbidden",
  notFound: "/not-found",
} as const;
