import { Tag } from "antd";

type SmartStatusTone = "info" | "success" | "warning" | "danger" | "system" | "neutral";

const STATUS_TONES: Record<string, SmartStatusTone> = {
  VALID: "success",
  WARNING: "warning",
  INVALID: "danger",
  NOT_VALIDATED: "neutral",
  VALIDATED: "success",
  HAS_ERRORS: "danger",
  READY_TO_VALIDATE: "info",
  DRAFT: "neutral",
  VALIDATING: "info",
  FAILED: "danger",
  APPLIED: "success",
  NORMAL: "success",
  SUCCESS: "success",
  ERROR: "danger",
  WAITING: "neutral",
  PROCESSING: "info",
  IN_PROGRESS: "info",
  COMPLETED: "success",
  CREATED: "success",
  DONE: "success",
  READY: "info",
  READY_FOR_INTAKE: "success",
  READY_FOR_PROCESSING: "info",
  HOLD: "warning",
  PENDING: "warning",
  NEEDS_REVIEW: "warning",
  TEAM_ASSIGN_PENDING: "warning",
  PRODUCT_MATCH_PENDING: "warning",
  RETURN_TRACKING_PENDING: "warning",
  BLOCKED: "danger",
  REJECTED: "danger",
  CANCELLED: "neutral",
  INACTIVE: "neutral",
  DISABLED: "neutral",
  SKIPPED: "neutral",
  SHORTAGE: "warning",
  OVERAGE: "warning",
  UNREGISTERED: "danger",
  DUPLICATED: "warning",
  ACTIVE: "success",
  CONNECTED: "success",
  EXPIRED: "warning",
  AUTH_REQUIRED: "warning",
  NOT_CONNECTED: "neutral",
  RUNNING: "info",
  PARTIAL_SUCCESS: "warning",
  RECEIVED: "info",
  NORMALIZED: "success",
  DUPLICATE_SKIPPED: "neutral",
  NEEDS_INPUT: "warning",
  MATCHED: "success",
  MISMATCHED: "danger",
  NO_TARGET: "neutral",
  GOOD: "success",
  CHANNEL_API: "info",
  NAVER_SMARTSTORE: "system",
  MANUAL: "neutral",
  AUTO_APPLY: "success",
  LOW_CONFIDENCE: "warning",
  ACCEPTED: "success",
  CORRECTED: "info",
  CONFLICT: "danger",
  CONFIG: "system",
  ADMIN: "system",
  PERMISSION: "system",
  SYNC: "system",
  정상: "success",
  경고: "warning",
  오류: "danger",
  대기: "neutral",
  처리중: "info",
  완료: "success",
  보류: "warning",
  취소: "neutral",
  비활성: "neutral",
  수량부족: "warning",
  수량초과: "warning",
  미등록: "danger",
  중복: "warning",
};

const STATUS_LABELS: Record<string, string> = {
  VALID: "정상",
  WARNING: "경고",
  INVALID: "오류",
  NOT_VALIDATED: "검증 전",
  VALIDATED: "검증 완료",
  HAS_ERRORS: "오류 있음",
  READY_TO_VALIDATE: "검증 대기",
  DRAFT: "작성 중",
  VALIDATING: "검증 중",
  FAILED: "실패",
  APPLIED: "확정 완료",
  NORMAL: "정상",
  SUCCESS: "정상",
  ERROR: "오류",
  WAITING: "대기",
  PROCESSING: "처리중",
  COMPLETED: "완료",
  HOLD: "보류",
  CANCELLED: "취소",
  INACTIVE: "비활성",
  SHORTAGE: "수량부족",
  OVERAGE: "수량초과",
  UNREGISTERED: "미등록",
  DUPLICATED: "중복",
};

export function SmartStatusBadge({
  status,
  label,
  tone: toneOverride,
}: {
  status?: string | null;
  label?: string;
  tone?: SmartStatusTone;
}) {
  const value = status || "DRAFT";
  const normalizedValue = String(value).toUpperCase();
  const tone = toneOverride || STATUS_TONES[normalizedValue] || STATUS_TONES[value] || "neutral";
  return (
    <Tag className={`smart-status-badge smart-status-badge--${tone}`}>
      {label || STATUS_LABELS[value] || STATUS_LABELS[normalizedValue] || value}
    </Tag>
  );
}
